### PR TITLE
Please Push Packages Properly Preferring Python

### PR DESCRIPTION
**Pull request by kojiromike**
Sorry for the title. Alliteration is Awesome.

### CODE REVIEW

**Comment by jeremycarroll** [comment]
I will try this on syapse-ontology as my review.

**Comment by jeremycarroll** [comment]
@kojiromike I don't really understand the motivation here. Is there something wrong in using packagecloud's ruby script? Does it not do exactly what you coded up, just that they did it, and we did not. I wonder whether this PR is a 'not invented here' ...

You have replaced 3 lines of code with 24 ... that is a cost ...

**Comment by kojiromike** [comment]
@jeremycarroll My issue is with using two containers, which you have to both fetch and also copy the package from one to the other. I'm not married to this solution, but I definitely dislike carrying the package across containers just to push it.

**Comment by jeremycarroll** [comment]
@kojiromike This PR does not address the 'carrying the package across containers to push it'. I think the motivation for that is actually to test it. The workflow is build - test + test + test - release. Each of these steps is in a different container, and there is that sequence, so unless we do all of that in one container we do need to have a final container for the pushing: I don't think there is much real cost on circleci to making it a ruby container that does this step

**Comment by kojiromike** [comment]
Will revisit this later.

**Pull request closed without merging**
